# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import main_menu.game_pb2 as game__pb2


class GameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GameSetup = channel.unary_unary(
                '/game.Game/GameSetup',
                request_serializer=game__pb2.Setup.SerializeToString,
                response_deserializer=game__pb2.EngineResponse.FromString,
                )
        self.MakeMove = channel.unary_unary(
                '/game.Game/MakeMove',
                request_serializer=game__pb2.Move.SerializeToString,
                response_deserializer=game__pb2.EngineResponse.FromString,
                )


class GameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GameSetup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GameSetup': grpc.unary_unary_rpc_method_handler(
                    servicer.GameSetup,
                    request_deserializer=game__pb2.Setup.FromString,
                    response_serializer=game__pb2.EngineResponse.SerializeToString,
            ),
            'MakeMove': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeMove,
                    request_deserializer=game__pb2.Move.FromString,
                    response_serializer=game__pb2.EngineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game.Game', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Game(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GameSetup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.Game/GameSetup',
            game__pb2.Setup.SerializeToString,
            game__pb2.EngineResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MakeMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.Game/MakeMove',
            game__pb2.Move.SerializeToString,
            game__pb2.EngineResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
