# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x04game\",\n\x05Setup\x12\x11\n\tboardSize\x18\x01 \x01(\x05\x12\x10\n\x08gameMode\x18\x02 \x01(\x05\"P\n\x04Move\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x02 \x01(\x05\x12\x0e\n\x06subRow\x18\x03 \x01(\x05\x12\x0e\n\x06subCol\x18\x04 \x01(\x05\x12\x0e\n\x06player\x18\x05 \x01(\x05\"o\n\x0e\x45ngineResponse\x12\x0f\n\x07gameWon\x18\x01 \x01(\x05\x12\x12\n\nsubCellWon\x18\x02 \x01(\x05\x12\x0b\n\x03row\x18\x03 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x04 \x01(\x05\x12\x0e\n\x06subRow\x18\x05 \x01(\x05\x12\x0e\n\x06subCol\x18\x06 \x01(\x05\x32\x64\n\x04Game\x12.\n\tGameSetup\x12\x0b.game.Setup\x1a\x14.game.EngineResponse\x12,\n\x08MakeMove\x12\n.game.Move\x1a\x14.game.EngineResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETUP._serialized_start=20
  _SETUP._serialized_end=64
  _MOVE._serialized_start=66
  _MOVE._serialized_end=146
  _ENGINERESPONSE._serialized_start=148
  _ENGINERESPONSE._serialized_end=259
  _GAME._serialized_start=261
  _GAME._serialized_end=361
# @@protoc_insertion_point(module_scope)
